name: Runs BDD Automated UI Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4


      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean -Dtest="createAccount.CreateAccountTest,
          addProductsToCompareList.AddProductsToCompareListTest"